name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: python test
      run: |
        python3 --version
        python test.py
    - name: cmake test
      run: |
        mkdir build && cd build
        cmake ..
        make
        ./main
    - name: unity3d test
      env:
         U_USERNAME: ${{ secrets.UNITY_USERNAME }}
         U_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      run: |
        /usr/bin/docker pull gableroux/unity3d:2018.2.6f1
        docker images
        #/usr/bin/docker run -it --rm -e "UNITY_USERNAME=$U_USERNAME" -e "UNITY_PASSWORD=$U_PASSWORD" -e "TEST_PLATFORM=linux" -e "WORKDIR=/root/project" -v "$(pwd):/root/project" docker.io/gableroux/unity3d:2018.2.6f1
        pwd
        uname -a 
        cat /etc/*release
        ls /opt
        #xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' /opt/Unity/Editor/Unity -logFile /dev/stdout -batchmode -username "$UNITY_USERNAME" -password "$UNITY_PASSWORD"
        #exit
      
    

