name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: python test
      run: |
        python3 --version
        python test.py
    - name: cmake test
      run: |
        mkdir build && cd build
        cmake ..
        make
        ./main
    - name: unity3d test
    - uses: docker://gableroux/unity3d:2018.2.6f1
      run: |
        pwd
        uname -a
        cat /etc/*release
        ls /opt

