name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: python test
      run: |
        python3 --version
        python test.py
    - name: cmake test
      run: |
        mkdir build && cd build
        cmake ..
        make
        ./main
    - name: unity3d test
      env:
         U_USERNAME: ${{ secrets.UNITY_USERNAME }}
         U_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      uses: gableroux/unity3d:2018.2.6f1
      with:
        entrypoint: /bin/bash
        args: xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' /opt/Unity/Editor/Unity -logFile /dev/stdout -batchmode -username "$UNITY_USERNAME" -password "$UNITY_PASSWORD"
    
      
    

