name: ci-new
on: [push]

jobs:
  j-01:
    runs-on: ubuntu-latest
    steps:
    - name: create file
      run: echo "create filesss" >> 01.txt
    - name: Cache
      uses: actions/cache@v2.1.5
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: 01.txt
        # An explicit key for restoring and saving the cache
        key: key-01
  j-02:
    runs-on: macos-latest
    steps:
    - name: create file
      run: echo "create filesss000000" >> 02.txt
    - name: Cache
      uses: actions/cache@v2.1.5
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: 02.txt
        # An explicit key for restoring and saving the cache
        key: key-02
  j-04:
    runs-on: windows-latest
    steps:
    - name: create file
      run: |
        echo "create filesss0asssssssssssssss00000" >> 02.txt
        md kkk\sshh
        copy 02.txt kkk\sshh
        dir kkk\sshh
    - name: curl
      uses: enflo/curl-action@master
      with:
        curl: " -T kkk/sshh/02.txt --url  https://dav.jianguoyun.com/dav/wanderer-sdk/kkk/sshh/02.txt -u \"{{ secrets.WEBDAV_NAME }}:{{ secrets.WEBDAV_PASSWORD }}\""

  j-03:
    runs-on: ubuntu-latest
    needs: [j-01,j-02,j-04]
    steps:
    - name: Cache - 02
      uses: actions/cache@v2.1.5
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: 02.txt
        # An explicit key for restoring and saving the cache
        key: key-02
    - name: Cache - 01
      uses: actions/cache@v2.1.5
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: 01.txt
        # An explicit key for restoring and saving the cache
        key: key-01
    - name: curl
      uses: enflo/curl-action@master
      with:
        curl: " -O  https://dav.jianguoyun.com/dav/wanderer-sdk/kkk/sshh/02.txt -u \"{{ secrets.WEBDAV_NAME }}:{{ secrets.WEBDAV_PASSWORD }}\""
    - name: show files
      run: |
        ls -alh
        cat 01.txt
        cat 02.txt
        cat kkk/sshh/02.txt
    
